/// <reference path="../typings/tsd.d.ts"/>
/// <reference path="../config/config.ts" />
/// <reference path="../objects/label.ts" />
/// <reference path="../objects/button.ts" />
/// <reference path="../objects/scene.ts" />
/// <reference path="../scenes/over.ts" />
/// <reference path="../scenes/win.ts" />
/// <reference path="../scenes/play.ts" />
/// <reference path="../scenes/menu.ts" />
/// <reference path="../scenes/slide1.ts" />
/// <reference path="../scenes/slide2.ts" />
/// <reference path="../scenes/slide3.ts" />
/// <reference path="../scenes/slide4.ts" />
/// <reference path="../scenes/slide6.ts" />
/// <reference path="../scenes/slide7.ts" />
/// <reference path="../scenes/slide8.ts" />
/// <reference path="../scenes/slide9.ts" /> 
//# sourceMappingURL=_reference.js.map